/**
 * Generates the contents of `src/generated/` from the SVG sources shipped by
 * `remixicon`.
 *
 * Remix icons are all single-`<path>`, 24x24 glyphs with no presentation
 * attributes, which is what lets us reduce each one to a bare path string and
 * render it through a single shared container component.
 *
 * Run with `npm run generate` from the package root.
 */
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";

const require = createRequire(import.meta.url);
const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(packageRoot, "src", "generated");
const componentsDir = join(outDir, "components");
const pathsDir = join(outDir, "paths");

const remixiconRoot = dirname(require.resolve("remixicon/package.json"));
const remixiconVersion = JSON.parse(readFileSync(join(remixiconRoot, "package.json"), "utf8")).version;
const iconsRoot = join(remixiconRoot, "icons");

const BANNER = `/*
 * This file is generated by scripts/generate-icons.mjs — do not edit it by hand.
 *
 * Glyphs are sourced from remixicon@${remixiconVersion} (Apache-2.0).
 */
`;

/** `add-line` -> `AddLine`. Names that would start with a digit get an `Icon` prefix. */
function toComponentName(iconName) {
    const pascal = iconName
        .split(/[^a-zA-Z0-9]+/)
        .filter(Boolean)
        .map(part => part.charAt(0).toUpperCase() + part.slice(1))
        .join("");
    return /^[0-9]/.test(pascal) ? `Icon${pascal}` : pascal;
}

/** `add-line` -> `ADD_LINE`, the `IconNames` member name. */
function toConstantName(iconName) {
    const constant = iconName.replace(/[^a-zA-Z0-9]+/g, "_").toUpperCase();
    return /^[0-9]/.test(constant) ? `_${constant}` : constant;
}

/** `add-line` -> `ADD_LINE_PATH`, the name of the shared path constant. */
function toPathConstantName(iconName) {
    return `${toConstantName(iconName)}_PATH`;
}

/** `User & Faces` -> `UserFaces`, the per-category component module name. */
function toModuleName(category) {
    return category
        .split(/[^a-zA-Z0-9]+/)
        .filter(Boolean)
        .map(part => part.charAt(0).toUpperCase() + part.slice(1))
        .join("");
}

function extractPath(svg, file) {
    const paths = [...svg.matchAll(/<path\b[^>]*\bd="([^"]+)"[^>]*>/g)].map(match => match[1]);
    if (paths.length !== 1) {
        throw new Error(`Expected exactly one <path> in ${file}, found ${paths.length}`);
    }
    if (/<(circle|ellipse|g|line|polygon|polyline|rect)\b/.test(svg)) {
        throw new Error(`${file} contains shapes other than <path>, which the generator cannot represent`);
    }
    const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
    if (viewBox !== "0 0 24 24") {
        throw new Error(`Expected a 24x24 viewBox in ${file}, found "${viewBox}"`);
    }
    return paths[0];
}

const categories = readdirSync(iconsRoot, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .sort();

/** @type {Map<string, {name: string, path: string, category: string}>} */
const icons = new Map();
/** @type {Map<string, string[]>} */
const iconsByCategory = new Map();
/** @type {Map<string, string>} */
const componentNames = new Map();

for (const category of categories) {
    const files = readdirSync(join(iconsRoot, category))
        .filter(file => file.endsWith(".svg"))
        .sort();
    const names = [];

    for (const file of files) {
        const name = file.slice(0, -".svg".length);
        if (icons.has(name)) {
            throw new Error(`Duplicate icon name "${name}" (${icons.get(name).category} and ${category})`);
        }
        const componentName = toComponentName(name);
        if (componentNames.has(componentName)) {
            throw new Error(
                `Icons "${componentNames.get(componentName)}" and "${name}" both map to component <${componentName}>`,
            );
        }
        componentNames.set(componentName, name);

        const svgPath = extractPath(readFileSync(join(iconsRoot, category, file), "utf8"), file);
        icons.set(name, { name, path: svgPath, category });
        names.push(name);
    }

    iconsByCategory.set(category, names);
}

const sortedIcons = [...icons.values()].sort((a, b) => (a.name < b.name ? -1 : 1));

rmSync(outDir, { force: true, recursive: true });
mkdirSync(componentsDir, { recursive: true });

// ---------------------------------------------------------------- iconNames.ts

writeFileSync(
    join(outDir, "iconNames.ts"),
    `${BANNER}
/**
 * The name of every icon in the set, as a lookup object. Prefer referencing
 * icons through this object rather than as raw strings so that renamed or
 * removed icons surface as compile errors.
 */
export const IconNames = {
${sortedIcons.map(icon => `    ${toConstantName(icon.name)}: "${icon.name}",`).join("\n")}
} as const;

/** The name of an icon in the set. */
export type IconName = (typeof IconNames)[keyof typeof IconNames];

/**
 * Every icon name, for runtime membership checks.
 *
 * Both calls are annotated so that bundlers can drop this set — and with it the
 * couple of thousand names it holds — from applications which never look an
 * icon up by name.
 */
export const IconNamesSet: ReadonlySet<string> = /* @__PURE__ */ new Set(/* @__PURE__ */ Object.values(IconNames));

/** Whether the given string names an icon in the set. */
export function isIconName(name: string | null | undefined): name is IconName {
    return name != null && IconNamesSet.has(name);
}
`,
);

// ------------------------------------------------------------ paths/<Category>

mkdirSync(pathsDir, { recursive: true });

for (const category of categories) {
    const moduleName = toModuleName(category);
    const names = iconsByCategory.get(category);

    writeFileSync(
        join(pathsDir, `${moduleName}.ts`),
        `${BANNER}
${names
    // Annotated \`string\` rather than left to inference so that the emitted
    // declarations do not repeat every path as a literal type.
    .map(name => `export const ${toPathConstantName(name)}: string =\n    "${icons.get(name).path}";`)
    .join("\n\n")}
`,
    );
}

// ---------------------------------------------------------------- iconPaths.ts

writeFileSync(
    join(outDir, "iconPaths.ts"),
    `${BANNER}
${categories.map(category => `import * as ${toModuleName(category)} from "./paths/${toModuleName(category)}";`).join("\n")}
import type { IconName } from "./iconNames";
import type { IconPaths } from "../icons/iconTypes";

/**
 * SVG path data for every icon, keyed by icon name. Referencing this record
 * pulls the whole icon set into your bundle; import individual icon components
 * instead if you only need a handful.
 */
export const IconSvgPaths: Record<IconName, IconPaths> = {
${sortedIcons
    .map(icon => `    "${icon.name}": [${toModuleName(icon.category)}.${toPathConstantName(icon.name)}],`)
    .join("\n")}
};
`,
);

// ----------------------------------------------------------- iconCategories.ts

writeFileSync(
    join(outDir, "iconCategories.ts"),
    `${BANNER}
import type { IconName } from "./iconNames";

/** The categories the icon set is grouped into, in display order. */
export const IconCategoryNames = [
${categories.map(category => `    "${category}",`).join("\n")}
] as const;

/** One of the categories the icon set is grouped into. */
export type IconCategory = (typeof IconCategoryNames)[number];

/** The icons belonging to each category. */
export const IconCategories: Record<IconCategory, IconName[]> = {
${categories
    .map(
        category =>
            `    "${category}": [\n${iconsByCategory
                .get(category)
                .map(name => `        "${name}",`)
                .join("\n")}\n    ],`,
    )
    .join("\n")}
};
`,
);

// ------------------------------------------------------- components/<Category>

for (const category of categories) {
    const moduleName = toModuleName(category);
    const names = iconsByCategory.get(category);

    const components = names
        .map(name => {
            const componentName = toComponentName(name);
            return `/** The \`${name}\` icon. */
export const ${componentName} = /* @__PURE__ */ createIcon("${componentName}", "${name}", [${toPathConstantName(name)}]);`;
        })
        .join("\n\n");

    writeFileSync(
        join(componentsDir, `${moduleName}.tsx`),
        `${BANNER}
import { createIcon } from "../../icons/createIcon";
import {
${names.map(name => `    ${toPathConstantName(name)},`).join("\n")}
} from "../paths/${moduleName}";

${components}
`,
    );
}

writeFileSync(
    join(componentsDir, "index.ts"),
    `${BANNER}
${categories.map(category => `export * from "./${toModuleName(category)}";`).join("\n")}
`,
);

console.log(
    `Generated ${sortedIcons.length} icons across ${categories.length} categories from remixicon@${remixiconVersion}.`,
);
